### ISSUE TITLE
I can't make it 

### ISSUE THREAD

**Issue by sd880131** [xia-lab/Seq2Fun#1]
when I try to make it，I got an error like：
fastqreader.o: In function `FastqReader::getBytes(unsigned long&, unsigned long&)':
fastqreader.cpp:(.text+0x555): undefined reference to `gzoffset'
writer.o: In function `Writer::init()':
writer.cpp:(.text+0x2e9): undefined reference to `gzbuffer'
collect2: error: ld returned 1 exit status
make: *** [seq2fun] Error 1
what can I do？

**Comment by rocpengliu** [comment]
Hello,
The most likely reason is that the zlib.
Could you please update your zlib and try it again?
