### ISSUE TITLE
Error during sample processing

### ISSUE THREAD

**Issue by asan-emirsaleh** [xia-lab/Seq2Fun#2]
I have an error during sample processing. The stdout otput is:
`[14:1:41] Protein (trans search) BWT of length 218460776 has been read with 480379 sequences, alphabet = *ACDEFGHIKLMNPQRSTVWY
[14:1:41] processing sample: A_rep1, 1 out of 9 samples

ERROR: Failed to open file: A_rep1_R1.fastq`
Also I attached my samples file
[sample.txt](https://github.com/xia-lab/Seq2Fun/files/6433941/sample.txt)

**Comment by rocpengliu** [comment]
Hi,
the most likely reason is that the file path.
Seq2Fun supports the full path of each sample.
Please try this (sample file must be seperated by "\t"):
A_rep1	filepath/A_rep1_R1.fastq	filepath/A_rep1_R2.fastq	cond_A
A_rep2	filepath/A_rep2_R1.fastq	filepath/A_rep2_R2.fastq	cond_A
A_rep3	filepath/A_rep3_R1.fastq	filepath/A_rep3_R2.fastq	cond_A
B_rep1	filepath/B_rep1_R1.fastq	filepath/B_rep1_R2.fastq	cond_B
B_rep2	filepath/B_rep2_R1.fastq	filepath/B_rep2_R2.fastq	cond_B
B_rep3	filepath/B_rep3_R1.fastq	filepath/B_rep3_R2.fastq	cond_B
C_rep1	filepath/C_rep1_R1.fastq	filepath/C_rep1_R2.fastq	cond_C
C_rep2	filepath/C_rep2_R1.fastq	filepath/C_rep2_R2.fastq	cond_C
C_rep3	filepath/C_rep3_R1.fastq	filepath/C_rep3_R2.fastq	cond_C

**Comment by asan-emirsaleh** [comment]
Hi
Yes, this was an issue. Changing the sample.tsv to include fullpath for each read done job. Thank you. Your tool is amazing. It worked in 33 min for 9 samples at 16 core workstation.

P.S.: I changed dir to that includes my reads before running the tool. But only by using fullpath job processed succesfully.

**Comment by rocpengliu** [comment]
it should work if you execute seq2fun in the same directory with your
sample.txt.


By the way, we are working on a website tool to process the downstream
analysis of seq2fun KO table although the website is not fully functional
at the moment.

https://www.networkanalyst.ca/NetworkAnalyst/uploads/TableUploadView.xhtml

all you need to do is slightly modify the ko table by following the sample
below.

NAME A1.CE2-S1-LT A2.CE2-M4-LT B1.CE2-S2-LT B2.CE2-M5-LT C1.CE2-S3-LT
C2.CE2-H1-LT CE2-S1-LT D1.CE2-S4-LT D2.CE2-H2-LT E1.CE2-S5-LT E2.CE2-H3-LT
F1.CE2-M1-LT F2.CE2-H4-LT G1.CE2-M2-LT G2.CE2-H5-LT H1.CE2-M3-LT
#CLASS:Dose Control Medium Control Medium Control High Control Control High
Control High Medium High Medium High High
K07436 0 0 402 0 0 0 1 2 0 0 1 0 1 6 4 1
K00700 324 397 567 322 360 398 169 371 293 279 371 355 414 339 253 262
K00700 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
K04078 0 4 0 1 3 0 1 3 1 4 2 2 1 4 0 2
K04078 0 0 0 0 0 0 0 0 3 0 0 0 0 0 0 0
K01112 913 937 1575 844 818 847 808 1383 703 1016 999 1014 971 844 828 656
K01112 0 0 0 0 0 1 1 0 0 0 1 0 1 0 0 1
K01112 120 163 196 136 126 118 140 176 124 144 139 218 135 107 99 103
K00069 2271 2463 541 1770 2003 2126 2034 2071 1998 1755 3358 2199 1722 2216
2032 1427
K06830 1355 1973 292 906 1672 1057 1366 2023 987 985 1836 1216 996 1139
1201 844

Then, go to the website
-> specify organisms -> KEGG orthology(generic)
-> choose file (your modified KO abundance table)
-> click to submit
-> you can explore the various functions on the website.
-> download the DEG tables and use your R script to do the pathway analysis.

Please give a try if you like using our website.
