### ISSUE TITLE
Seq2Fun not providing any mappings for Lemna minor 50bp single-read

### ISSUE THREAD

**Issue by hreinwal** [xia-lab/Seq2Fun#3]
Dear Seq2Fun-Team,

I am trying to map my RNASeq reads (~50bp SE) from _Lemna minor_ using Seq2Fun to the plantDb provided from your website.

Currently I am running:
`$seq2fun --thread 12 --profiling --n_base_limit 5 --sampletable seq2fun_sampleTable.tab --mode tGREEDY --tfmi $FMI/seq2fun_db/plants/plants_v2.0.fmi --genemap $FMI/seq2fun_db/plants/plants_annotation_v2.0.txt --minscore 40 --minlength 9 --mismatch 5 --maxtranslength 60 `

As you can see I already reduced the mapping stringency by reducing the --minscore to 40 and allowing for 5 mismatches as well as allowing a minimum peptide length of 9 AA. Nevertheless, Seq2Fun is not able map any of the reads from my provided fastq files. I checked, their quality is pretty good so this can not be the problem. Also Seq2Fun does not post any error messages. 

Do you have any advise for me? I would be delighted if you could reach out to me. I would be happy to share some example files with you. 

Thanks a lot in advance!

P.S. I know there is a reference genome for this organism and I used STAR to map the reads to it, which worked like a charm. So the reads in the fastq files should be ok.

**Comment by rocpengliu** [comment]
Hello

Will it be possible to share a sample read file  (~10000 reads) to my email rocpengliu@gmail.com?
I can work on this issue.

Thank you.

Peng

**Comment by hreinwal** [comment]
Dear Peng,
I created a Zenodo repository [ [https://zenodo.org/record/6517151](https://zenodo.org/record/6517151) ] which contains the reduced sample files (250k reads) as well as the script I used for running seq2fun. I hope this will help to debug this issue. 
Thanks a lot!

**Comment by hreinwal** [comment]
Thanks to @rocpengliu for pointing me to the `--length_required` parameter (Default 60). By setting the the value < 50 it worked smoothly. Thx for your support! :)
`$seq2fun --thread 12 --profiling --n_base_limit 5 --sampletable seq2fun_sampleTable.tab --mode tGREEDY --tfmi $FMI/seq2fun_db/plants/plants_v2.0.fmi --genemap $FMI/seq2fun_db/plants/plants_annotation_v2.0.txt --minlength 9 --mismatch 3 --length_required 45`
